import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { requiresNativeUpdate } from '../src/api/updatePreflight.ts';
const source = readFileSync('src/components/android-update-overlay.tsx', 'utf8');
const fn = source.slice(source.indexOf('function shouldShowUpdateSheet('), source.indexOf('\nfunction isAndroidSigningKeyMigration('));
const js = ts.transpileModule(fn, { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText;
const show = new Function('requiresNativeUpdate', js + '\nreturn shouldShowUpdateSheet;')(requiresNativeUpdate);
const optional = { updateAvailable: true, delivery: 'native', required: false, latestBuild: 1005663 };
const preflight = { ok: true };
for (const status of ['ready', 'installing', 'permission_required', 'error']) {
 assert.equal(show(optional, {status,build:1005663}, null, null, preflight), true, `optional ${status} must remain visible`);
}
assert.equal(show(optional,{status:'idle'},null,null,preflight),false);
assert.equal(show(optional,{status:'ready'},1005663,null,preflight),false);
assert.equal(show(optional,{status:'ready'},null,1005663,preflight),false);
assert.equal(show({...optional,required:true},{status:'error'},1005663,null,preflight),true);
assert.equal(show({...optional,updateAvailable:false},{status:'error'},null,null,preflight),false);
assert.equal(show({...optional,delivery:'ota'},{status:'ready'},null,null,preflight),false);
assert.equal(show(optional,{status:'error'},null,null,{ok:false}),false);
const bannerSource=readFileSync('src/components/update-center.tsx','utf8');
const bannerFn=bannerSource.slice(bannerSource.indexOf('function MobileUpdateNoticeBannerContent('),bannerSource.indexOf('\nfunction MobileUpdateCenterButton('));
const bannerJS=ts.transpileModule(bannerFn,{compilerOptions:{target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const render=update=>new Function('React','useMobileAppUpdateQuery','currentNativeBuild','requiresNativeUpdate','isAndroidSigningKeyMigration','Pressable','View','Text','ShieldAlert','styles',bannerJS+'\nreturn MobileUpdateNoticeBannerContent({onOpen:()=>{},platform:"android"});')({createElement:(type,props,...children)=>({type,props,children})},()=>({data:update}),()=>1005662,requiresNativeUpdate,()=>false,'Pressable','View','Text','ShieldAlert',{});
const optionalBanner=render(optional);
assert.equal(optionalBanner.props.accessibilityLabel,'Открыть обновление');
assert.match(JSON.stringify(optionalBanner),/Доступно обновление VEX/);
const requiredBanner=render({...optional,required:true});
assert.equal(requiredBanner.props.accessibilityLabel,'Открыть обязательное обновление');
assert.match(JSON.stringify(requiredBanner),/Требуется обновление VEX/);
assert.equal(render({...optional,updateAvailable:false}),null);
console.log('ANDROID_UPDATE_UI_POLICY=PASS: optional progress/error/permission visible; optional and required labels distinct');

assert.equal(render({...optional,currentBuildBlocked:true}).props.accessibilityLabel,'Открыть обязательное обновление');
const dismissSource=source.slice(source.indexOf('  const handleDismiss = useCallback('),source.indexOf('\n\n  const handleOpenManualDownload'));
const dismissJS=ts.transpileModule(dismissSource,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
let dismissed=0,deleted=0;
const busyGate={isRunning:()=>true};
const dismiss=new Function('useCallback','update','installGate','setDismissedBuild','playSelectionHaptic','SecureStore','pendingAndroidInstallKey',dismissJS+';return handleDismiss;')(fn=>fn,optional,busyGate,()=>dismissed++,()=>{}, {deleteItemAsync:async()=>{deleted++;}},'fixture');
dismiss();
assert.equal(dismissed,0,'hardware back must not dismiss an in-flight installation');
assert.equal(deleted,0,'in-flight pending marker must remain');
console.log('ANDROID_UPDATE_BUSY_DISMISS=PASS');
const { createAndroidUpdateInstallGate }=await import('../src/components/android-update-install-gate.ts');
const gate=createAndroidUpdateInstallGate();
let complete,starts=0;
const pending=gate.run(async()=>{starts++;await new Promise(resolve=>{complete=resolve;});});
assert.equal(gate.isRunning(),true);
for(let i=0;i<5;i++)assert.equal(await gate.run(async()=>{starts++;}),false,'rapid press/foreground resume cannot overlap');
assert.equal(starts,1);
complete();assert.equal(await pending,true);assert.equal(gate.isRunning(),false);
assert.equal(await gate.run(async()=>{starts++;}),true,'permission return after completed attempt can retry');
await assert.rejects(gate.run(async()=>{throw Error('fixture failure');}));
assert.equal(gate.isRunning(),false,'failure must release gate');
assert.equal(await gate.run(async()=>{}),true);
assert.match(source,/cancelled \|\| restoring \|\| installGate\.isRunning\(\)/,'resume must check shared gate before touching pending state');
assert.match(source,/<Button disabled=\{downloadState\.status === 'installing'\} label=\{update.required/);
console.log('ANDROID_UPDATE_SINGLE_FLIGHT=PASS: concurrent/repeated/resume suppressed, permission retry allowed, failure releases');
const restoreSource=source.slice(source.indexOf('    const restorePendingInstall = async () => {'),source.indexOf('\n    void restorePendingInstall();'));
const restoreJS=ts.transpileModule(restoreSource,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
let readResolve,restoreStates=0,autoInstalls=0,storeWrites=0,busy=false;
const makeRestore=()=>new Function('SecureStore','installGate','setDownloadState','parsePendingAndroidInstall','pendingAndroidInstallKey','update','performInstall','let cancelled=false,restoring=false;'+restoreJS+';return {run:restorePendingInstall,cancel:()=>{cancelled=true;}};')({getItemAsync:()=>new Promise(r=>readResolve=r),setItemAsync:async()=>{storeWrites++;}}, {isRunning:()=>busy},()=>restoreStates++,JSON.parse,'fixture',optional,async()=>{autoInstalls++;});
const restore=makeRestore();const reading=restore.run();busy=true;
readResolve(JSON.stringify({build:1005663,resumeAttempted:false}));await reading;
assert.equal(restoreStates,0,'stale restore read must not overwrite a newly started manual install');
busy=false;const cancelledRestore=makeRestore();const cancelledReading=cancelledRestore.run();cancelledRestore.cancel();readResolve(JSON.stringify({build:1005663,resumeAttempted:false}));await cancelledReading;
assert.equal(restoreStates,0,'unmounted effect cannot restore state');
const idleRestore=makeRestore();const idleReading=idleRestore.run();readResolve(JSON.stringify({build:1005663,resumeAttempted:false}));await idleReading;
assert.equal(restoreStates,1);assert.equal(autoInstalls,0,'native owns automatic permission return; JS restore is read-only');assert.equal(storeWrites,0);
console.log('ANDROID_UPDATE_RESTORE_RACES=PASS: busy/cancelled stale reads ignored; no duplicate automatic native install');
