import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { buildAppWebAuthUrl } from '../src/auth/webAuthUrl';

const input = { baseUrl: 'https://example.invalid/', challenge: 'fixture-challenge', deviceId: 'fixture-device', deviceName: 'Fixture & Device', platform: 'android', state: 'fixture-state' };
const ordinary = new URL(buildAppWebAuthUrl(input));
const google = new URL(buildAppWebAuthUrl({ ...input, provider: 'google' }));
assert.equal(google.searchParams.get('provider'), 'google');
assert.equal(ordinary.searchParams.has('provider'), false);
assert.equal(google.pathname, '/auth/app');
for (const [key, value] of ordinary.searchParams) assert.equal(google.searchParams.get(key), value);
assert.equal(google.searchParams.get('state'), input.state);
assert.equal(google.searchParams.get('code_challenge'), input.challenge);
const screen = readFileSync('src/screens/sign-in-screen.tsx', 'utf8');
assert.match(screen, /handleWebAuthStart\("google"\)/);
assert.match(screen, /Войти через Google/);
assert.doesNotMatch(screen, /mfaCode|setMfaCode|Код аутентификатора/);
assert.match(screen, /code.length !== 6/);
const api = readFileSync('src/api/auth.ts', 'utf8');
assert.doesNotMatch(api, /mfa_code|mfaCode/);
assert.match(api, /device_session: true/);
const otp = readFileSync('src/components/otp-code-input.tsx', 'utf8');
assert.match(otp, /one-time-code/);
const service = readFileSync('macos-native/Sources/VEXNativeMac/Services/PKCEAuthService.swift', 'utf8');
assert.match(service, /URLQueryItem\(name: "provider", value: provider.rawValue\)/);
assert.match(service, /ASWebAuthenticationSession/);
assert.match(service, /storedState == returnedState/);
const state = readFileSync('macos-native/Sources/VEXNativeMac/Stores/VEXAppState.swift', 'utf8');
assert.match(state, /beginWebAuth\(mode: \.login, provider: \.google\)/);
assert.match(state, /startWebAuth\(mode: mode, provider: provider\)/);
const panel = readFileSync('macos-native/Sources/VEXNativeMac/Views/SignInPanel.swift', 'utf8');
assert.match(panel, /appState.openGoogleSignIn\(\)/);
assert.match(panel, /Войти через Google/);
console.log('PASS: Google URL preserves PKCE/state; Android and macOS buttons use browser handoff; client OTP has no MFA input and retains six-digit/autofill checks');
