import { Platform, StyleSheet } from 'react-native';

import { vexTheme } from '@/ui/vex-theme';

export const maxContentWidth = 430;

export const styles = StyleSheet.create({
  shell: {
    gap: vexTheme.spacing.sm,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    gap: vexTheme.spacing.sm,
    paddingBottom: vexTheme.spacing.xl,
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mainContent: {
    gap: vexTheme.spacing.md,
    justifyContent: 'flex-start',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  centerStateText: {
    color: vexTheme.colors.textMuted,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 16,
  },
  authPanel: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(7,17,19,0.88)',
    borderColor: 'rgba(96,118,123,0.42)',
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    marginTop: 32,
    padding: 20,
  },
  authIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 82,
    justifyContent: 'center',
    width: 82,
  },
  authLogo: {
    height: 96,
    width: 96,
  },
  authTitle: {
    color: '#F4FCFD',
    fontSize: 27,
    fontWeight: '900',
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#A7B9BD',
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  input: {
    backgroundColor: 'rgba(2,10,11,0.78)',
    borderColor: 'rgba(96,118,123,0.46)',
    borderRadius: 18,
    borderWidth: 1,
    color: '#F4FCFD',
    fontSize: 17,
    minHeight: 56,
    paddingHorizontal: 16,
  },
  authError: {
    color: '#FF7A7A',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#22D3EE',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#031012',
    fontSize: 18,
    fontWeight: '900',
  },
  modeButton: {
    alignItems: 'center',
    minHeight: 42,
    justifyContent: 'center',
  },
  modeButtonText: {
    color: '#22D3EE',
    fontSize: 15,
    fontWeight: '800',
  },
  hero: {
    alignItems: 'center',
    minHeight: 270,
    justifyContent: 'flex-start',
    overflow: 'visible',
  },
  powerCluster: {
    alignItems: 'center',
    height: 222,
    justifyContent: 'center',
    position: 'relative',
    width: 222,
  },
  heroGlow: {
    backgroundColor: vexTheme.colors.accentMuted,
    borderRadius: 106,
    height: 194,
    left: 14,
    position: 'absolute',
    top: 14,
    width: 194,
  },
  heroGlowDesktopStatic: {
    opacity: 0.46,
    shadowOpacity: 0.26,
    shadowRadius: 12,
  },
  heroRing: {
    borderColor: vexTheme.colors.accentLine,
    borderRadius: 100,
    borderWidth: 1,
    height: 184,
    left: 19,
    position: 'absolute',
    top: 19,
    width: 184,
  },
  heroRingOuter: {
    borderColor: 'rgba(121,239,247,0.08)',
    borderRadius: 110,
    borderWidth: 2,
    height: 210,
    left: 6,
    position: 'absolute',
    top: 6,
    width: 210,
  },
  heroRingOuterDesktopStatic: {
    opacity: 0.5,
  },
  powerButtonFrame: {
    alignItems: 'center',
    backgroundColor: vexTheme.colors.surfaceRaised,
    borderColor: vexTheme.colors.accent,
    borderRadius: 86,
    borderWidth: 4,
    height: 168,
    justifyContent: 'center',
    width: 168,
  },
  powerButtonFrameDesktop: {
    shadowOpacity: 0.34,
    shadowRadius: 12,
  },
  powerButtonFrameActive: {
    backgroundColor: '#0B2423',
    borderColor: vexTheme.colors.success,
  },
  powerButtonBusy: {
    opacity: 0.72,
  },
  powerButton: {
    alignItems: 'center',
    borderRadius: 86,
    height: '100%',
    justifyContent: 'center',
    overflow: 'hidden',
    width: '100%',
  },
  powerOrbit: {
    borderColor: 'transparent',
    borderBottomColor: vexTheme.colors.accentMuted,
    borderRadius: 72,
    borderRightColor: vexTheme.colors.accentMuted,
    borderTopColor: vexTheme.colors.accentStrong,
    borderWidth: 4,
    height: 142,
    position: 'absolute',
    width: 142,
  },
  powerText: {
    color: vexTheme.colors.text,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 34,
    marginTop: 5,
    maxWidth: 280,
    minWidth: 0,
    textAlign: 'center',
  },
  powerSubtext: {
    color: vexTheme.colors.textSecondary,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 2,
    textAlign: 'center',
  },
  protocolSpacer: {
    alignSelf: 'center',
    minHeight: 2,
  },
  serverChip: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: vexTheme.colors.surface,
    borderColor: vexTheme.colors.line,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    maxWidth: maxContentWidth,
    minHeight: 78,
    paddingHorizontal: 16,
    width: '100%',
  },
  serverChipSelected: {
    borderColor: vexTheme.colors.accent,
  },
  serverChipDisabled: {
    opacity: 0.72,
  },
  serverChipFlag: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  serverChipFlagText: {
    fontSize: 30,
  },
  serverChipCountryIsland: {
    position: 'absolute',
    right: 76,
  },
  serverChipCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverChipCaption: {
    color: vexTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 3,
  },
  serverChipLabel: {
    color: vexTheme.colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 2,
    minWidth: 0,
  },
  serverLatencyPill: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    flexDirection: 'row',
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minWidth: 48,
  },
  serverLatencyText: {
    color: vexTheme.colors.accentStrong,
    fontSize: 16,
    fontWeight: '900',
  },
  locationsSection: {
    gap: vexTheme.spacing.sm,
  },
  locationCarousel: {
    width: '100%',
  },
  locationCarouselItem: {
    marginRight: vexTheme.spacing.sm,
  },
  locationsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  locationsTitle: {
    color: vexTheme.colors.text,
    fontSize: 21,
    fontWeight: '900',
  },
  locationsAllButton: {
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 8,
  },
  locationsAllText: {
    color: vexTheme.colors.accentStrong,
    fontSize: 16,
    fontWeight: '800',
  },
  serverSelectedIcon: {
    alignItems: 'center',
    backgroundColor: vexTheme.colors.accent,
    borderRadius: 18,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  trafficStats: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: vexTheme.spacing.sm,
    maxWidth: maxContentWidth,
    width: '100%',
  },
  trafficCard: {
    backgroundColor: vexTheme.colors.surfaceMuted,
    borderColor: vexTheme.colors.line,
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    minHeight: 100,
    minWidth: 0,
    padding: 10,
  },
  trafficCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  trafficLabel: {
    color: vexTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  trafficValue: {
    color: vexTheme.colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 5,
  },
  trafficSparkline: {
    marginTop: 4,
  },
  trafficDirectionBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.1)',
    borderColor: vexTheme.colors.accent,
    borderRadius: 18,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  heroRingFar: {
    borderColor: 'rgba(121,239,247,0.07)',
    borderRadius: 132,
    borderWidth: 1,
    height: 250,
    left: -14,
    position: 'absolute',
    top: -14,
    width: 250,
  },
  heroRingMid: {
    borderColor: 'rgba(121,239,247,0.12)',
    borderRadius: 122,
    borderWidth: 1,
    height: 230,
    left: -4,
    position: 'absolute',
    top: -4,
    width: 230,
  },
  serverModal: {
    backgroundColor: vexTheme.colors.background,
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: Platform.OS === 'android' ? 34 : 46,
  },
  serverDrawer: {
    backgroundColor: 'transparent',
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  serverModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  serverModalEyebrow: {
    color: '#22D3EE',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 4,
  },
  serverModalTitle: {
    color: '#F4FCFD',
    fontSize: 20,
    fontWeight: '900',
  },
  serverModalSubtitle: {
    color: '#8FBEC6',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 4,
    maxWidth: 240,
  },
  serverModalClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  serverModalList: {
    gap: 10,
    paddingBottom: 26,
  },
  serverRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(7,17,19,0.84)',
    borderColor: 'rgba(96,118,123,0.3)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 68,
    paddingHorizontal: 14,
  },
  serverRowSelected: {
    backgroundColor: 'rgba(34,211,238,0.14)',
    borderColor: '#22D3EE',
  },
  serverRowDisabled: {
    opacity: 0.62,
  },
  serverRowMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  serverRowFlag: {
    fontSize: 20,
    textAlign: 'center',
  },
  serverRowFlagBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(2,10,11,0.56)',
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  serverRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverRowName: {
    color: '#CFE4E8',
    fontSize: 15,
    fontWeight: '900',
  },
  serverRowNameSelected: {
    color: '#F4FCFD',
  },
  serverRowStatus: {
    color: '#8FBEC6',
    fontSize: 12,
    fontWeight: '700',
  },
  serverRowStatusLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 4,
    minWidth: 0,
  },
  serverHealthDot: {
    backgroundColor: '#78969C',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  serverHealthDotActive: {
    backgroundColor: '#22D3EE',
  },
  serverRowLatency: {
    color: '#A7B9BD',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  serverRowSide: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minWidth: 76,
    justifyContent: 'flex-end',
  },
  serverRowLatencySelected: {
    color: '#B9FBFF',
  },
  serverModalHint: {
    color: '#8FBEC6',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    paddingBottom: 18,
    textAlign: 'center',
  },
  vpnErrorText: {
    alignSelf: 'center',
    color: '#FF9F9F',
    fontSize: 12,
    fontWeight: '700',
    maxWidth: maxContentWidth - 32,
    textAlign: 'center',
  },
  vpnNoticeText: {
    color: vexTheme.colors.warning,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  rotationNotice: {
    alignSelf: 'center',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
