import { Platform, StyleSheet } from 'react-native';

export const maxContentWidth = 430;

export const styles = StyleSheet.create({
  shell: {
    gap: 10,
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mainContent: {
    flex: 1,
    gap: 10,
    justifyContent: 'space-between',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  centerStateText: {
    color: '#A7B9BD',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 16,
  },
  authPanel: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(7,17,19,0.88)',
    borderColor: 'rgba(96,118,123,0.42)',
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    marginTop: 32,
    padding: 20,
  },
  authIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 82,
    justifyContent: 'center',
    width: 82,
  },
  authLogo: {
    height: 96,
    width: 96,
  },
  authTitle: {
    color: '#F4FCFD',
    fontSize: 27,
    fontWeight: '900',
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#A7B9BD',
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  input: {
    backgroundColor: 'rgba(2,10,11,0.78)',
    borderColor: 'rgba(96,118,123,0.46)',
    borderRadius: 18,
    borderWidth: 1,
    color: '#F4FCFD',
    fontSize: 17,
    minHeight: 56,
    paddingHorizontal: 16,
  },
  authError: {
    color: '#FF7A7A',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#22D3EE',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#031012',
    fontSize: 18,
    fontWeight: '900',
  },
  modeButton: {
    alignItems: 'center',
    minHeight: 42,
    justifyContent: 'center',
  },
  modeButtonText: {
    color: '#22D3EE',
    fontSize: 15,
    fontWeight: '800',
  },
  hero: {
    alignItems: 'center',
    flex: 1,
    minHeight: 292,
    justifyContent: 'center',
    overflow: 'visible',
  },
  heroBackdrop: {
    alignItems: 'center',
    height: 292,
    justifyContent: 'center',
    opacity: 0.34,
    position: 'absolute',
    width: '100%',
  },
  heroNode: {
    backgroundColor: '#22D3EE',
    borderColor: 'rgba(185,251,255,0.5)',
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    position: 'absolute',
    shadowColor: '#22D3EE',
    shadowOpacity: 0.7,
    shadowRadius: 10,
    width: 10,
  },
  heroNodeTopLeft: {
    left: 28,
    top: 54,
  },
  heroNodeTopRight: {
    right: 42,
    top: 36,
  },
  heroLink: {
    backgroundColor: 'rgba(34,211,238,0.22)',
    height: 1,
    position: 'absolute',
    width: 168,
  },
  heroLinkOne: {
    left: 26,
    top: 86,
    transform: [{ rotate: '24deg' }],
  },
  heroGlow: {
    backgroundColor: 'rgba(34,211,238,0.16)',
    borderRadius: 124,
    height: 222,
    position: 'absolute',
    shadowColor: '#22D3EE',
    shadowOpacity: 0.74,
    shadowRadius: 28,
    width: 222,
  },
  heroGlowDesktopStatic: {
    opacity: 0.46,
    shadowOpacity: 0.26,
    shadowRadius: 12,
  },
  heroRing: {
    borderColor: 'rgba(34,211,238,0.34)',
    borderRadius: 122,
    borderWidth: 1,
    height: 228,
    position: 'absolute',
    width: 228,
  },
  heroRingOuter: {
    borderColor: 'rgba(185,251,255,0.08)',
    borderRadius: 134,
    borderWidth: 6,
    height: 242,
    position: 'absolute',
    width: 242,
  },
  heroRingOuterDesktopStatic: {
    opacity: 0.5,
  },
  powerButtonFrame: {
    alignItems: 'center',
    backgroundColor: 'rgba(3,17,20,0.94)',
    borderColor: '#35E6F4',
    borderRadius: 104,
    borderWidth: 7,
    height: 204,
    justifyContent: 'center',
    shadowColor: '#22D3EE',
    shadowOpacity: 0.94,
    shadowRadius: 24,
    width: 204,
  },
  powerButtonFrameDesktop: {
    shadowOpacity: 0.34,
    shadowRadius: 12,
  },
  powerButtonFrameActive: {
    backgroundColor: 'rgba(4,24,27,0.96)',
    borderColor: '#35E6F4',
    shadowColor: '#22D3EE',
  },
  powerButtonBusy: {
    opacity: 0.72,
  },
  powerButton: {
    alignItems: 'center',
    borderRadius: 102,
    height: '100%',
    justifyContent: 'center',
    overflow: 'hidden',
    width: '100%',
  },
  powerOrbit: {
    borderColor: 'transparent',
    borderBottomColor: 'rgba(34,211,238,0.22)',
    borderRadius: 89,
    borderRightColor: 'rgba(34,211,238,0.2)',
    borderTopColor: '#B9FBFF',
    borderWidth: 4,
    height: 174,
    position: 'absolute',
    width: 174,
  },
  powerText: {
    color: '#F4FCFD',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 28,
    maxWidth: 176,
    minWidth: 0,
    textAlign: 'center',
  },
  powerSubtext: {
    color: '#A8D8DE',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 8,
    textAlign: 'center',
  },
  protocolSpacer: {
    alignSelf: 'center',
    minHeight: 2,
  },
  serverChip: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(8,25,29,0.84)',
    borderColor: 'rgba(126,233,245,0.2)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    maxWidth: maxContentWidth,
    minHeight: 62,
    paddingHorizontal: 10,
    shadowColor: '#22D3EE',
    shadowOpacity: 0.1,
    shadowRadius: 14,
    width: '100%',
  },
  serverChipDisabled: {
    opacity: 0.72,
  },
  serverChipIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.13)',
    borderColor: 'rgba(34,211,238,0.2)',
    borderRadius: 14,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  serverChipCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverChipCaption: {
    color: '#8FBEC6',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  serverChipLabel: {
    color: '#EAF7F8',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
    minWidth: 0,
  },
  serverLatencyPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.11)',
    borderColor: 'rgba(34,211,238,0.44)',
    flexDirection: 'row',
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minWidth: 60,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  serverLatencyText: {
    color: '#B9FBFF',
    fontSize: 13,
    fontWeight: '900',
  },
  trafficStats: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(8,25,29,0.76)',
    borderColor: 'rgba(126,233,245,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    maxWidth: maxContentWidth,
    minHeight: 62,
    paddingHorizontal: 14,
    shadowColor: '#22D3EE',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    width: '100%',
  },
  trafficItem: {
    flex: 1,
    minWidth: 0,
  },
  trafficLabel: {
    color: '#8FBEC6',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  trafficValueRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginTop: 5,
  },
  trafficValue: {
    color: '#F4FCFD',
    fontSize: 19,
    fontWeight: '900',
  },
  trafficDirectionBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.12)',
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  trafficDivider: {
    backgroundColor: 'rgba(126,233,245,0.2)',
    height: 38,
    marginHorizontal: 14,
    width: 1,
  },
  serverModal: {
    backgroundColor: '#020A0B',
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'android' ? 34 : 46,
  },
  serverModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  serverModalEyebrow: {
    color: '#22D3EE',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 4,
  },
  serverModalTitle: {
    color: '#F4FCFD',
    fontSize: 20,
    fontWeight: '900',
  },
  serverModalSubtitle: {
    color: '#8FBEC6',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 4,
    maxWidth: 240,
  },
  serverModalClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  serverModalList: {
    gap: 7,
    paddingBottom: 18,
  },
  serverRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(7,17,19,0.84)',
    borderColor: 'rgba(96,118,123,0.3)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: 10,
  },
  serverRowSelected: {
    backgroundColor: 'rgba(34,211,238,0.14)',
    borderColor: '#22D3EE',
  },
  serverRowDisabled: {
    opacity: 0.62,
  },
  serverRowMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  serverRowFlag: {
    fontSize: 20,
    textAlign: 'center',
  },
  serverRowFlagBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(2,10,11,0.56)',
    borderRadius: 12,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  serverRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverRowName: {
    color: '#CFE4E8',
    fontSize: 15,
    fontWeight: '900',
  },
  serverRowNameSelected: {
    color: '#F4FCFD',
  },
  serverRowStatus: {
    color: '#8FBEC6',
    fontSize: 12,
    fontWeight: '700',
  },
  serverRowStatusLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 4,
    minWidth: 0,
  },
  serverHealthDot: {
    backgroundColor: '#78969C',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  serverHealthDotActive: {
    backgroundColor: '#22D3EE',
  },
  serverRowLatency: {
    color: '#A7B9BD',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  serverRowSide: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minWidth: 76,
    justifyContent: 'flex-end',
  },
  serverRowLatencySelected: {
    color: '#B9FBFF',
  },
  serverModalHint: {
    color: '#8FBEC6',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    paddingBottom: 18,
    textAlign: 'center',
  },
  vpnErrorText: {
    alignSelf: 'center',
    color: '#FF9F9F',
    fontSize: 12,
    fontWeight: '700',
    maxWidth: maxContentWidth - 32,
    textAlign: 'center',
  },
  vpnNoticeText: {
    alignSelf: 'center',
    color: '#F8D477',
    fontSize: 12,
    fontWeight: '700',
    maxWidth: maxContentWidth - 32,
    textAlign: 'center',
  },
  rotationNotice: {
    alignSelf: 'center',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
