import { Platform, StyleSheet } from 'react-native';

import { vexTheme } from '@/ui/vex-theme';

export const maxContentWidth = 430;

export const styles = StyleSheet.create({
  shell: {
    gap: vexTheme.spacing.sm,
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mainContent: {
    flex: 1,
    gap: vexTheme.spacing.sm,
    justifyContent: 'space-between',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  centerStateText: {
    color: vexTheme.colors.textMuted,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 16,
  },
  authPanel: {
    alignItems: 'stretch',
    backgroundColor: 'rgba(7,17,19,0.88)',
    borderColor: 'rgba(96,118,123,0.42)',
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    marginTop: 32,
    padding: 20,
  },
  authIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 82,
    justifyContent: 'center',
    width: 82,
  },
  authLogo: {
    height: 96,
    width: 96,
  },
  authTitle: {
    color: '#F4FCFD',
    fontSize: 27,
    fontWeight: '900',
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#A7B9BD',
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  input: {
    backgroundColor: 'rgba(2,10,11,0.78)',
    borderColor: 'rgba(96,118,123,0.46)',
    borderRadius: 18,
    borderWidth: 1,
    color: '#F4FCFD',
    fontSize: 17,
    minHeight: 56,
    paddingHorizontal: 16,
  },
  authError: {
    color: '#FF7A7A',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#22D3EE',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 56,
  },
  primaryButtonText: {
    color: '#031012',
    fontSize: 18,
    fontWeight: '900',
  },
  modeButton: {
    alignItems: 'center',
    minHeight: 42,
    justifyContent: 'center',
  },
  modeButtonText: {
    color: '#22D3EE',
    fontSize: 15,
    fontWeight: '800',
  },
  hero: {
    alignItems: 'center',
    flex: 1,
    minHeight: 250,
    justifyContent: 'center',
    overflow: 'visible',
  },
  powerCluster: {
    alignItems: 'center',
    height: 222,
    justifyContent: 'center',
    position: 'relative',
    width: 222,
  },
  heroGlow: {
    backgroundColor: vexTheme.colors.accentMuted,
    borderRadius: 110,
    height: 196,
    left: 13,
    position: 'absolute',
    top: 13,
    width: 196,
  },
  heroGlowDesktopStatic: {
    opacity: 0.46,
    shadowOpacity: 0.26,
    shadowRadius: 12,
  },
  heroRing: {
    borderColor: vexTheme.colors.accentLine,
    borderRadius: 104,
    borderWidth: 1,
    height: 190,
    left: 16,
    position: 'absolute',
    top: 16,
    width: 190,
  },
  heroRingOuter: {
    borderColor: 'rgba(121,239,247,0.08)',
    borderRadius: 112,
    borderWidth: 5,
    height: 206,
    left: 8,
    position: 'absolute',
    top: 8,
    width: 206,
  },
  heroRingOuterDesktopStatic: {
    opacity: 0.5,
  },
  powerButtonFrame: {
    alignItems: 'center',
    backgroundColor: vexTheme.colors.surfaceRaised,
    borderColor: vexTheme.colors.accent,
    borderRadius: 92,
    borderWidth: 5,
    height: 178,
    justifyContent: 'center',
    width: 178,
  },
  powerButtonFrameDesktop: {
    shadowOpacity: 0.34,
    shadowRadius: 12,
  },
  powerButtonFrameActive: {
    backgroundColor: '#0B2423',
    borderColor: vexTheme.colors.success,
  },
  powerButtonBusy: {
    opacity: 0.72,
  },
  powerButton: {
    alignItems: 'center',
    borderRadius: 90,
    height: '100%',
    justifyContent: 'center',
    overflow: 'hidden',
    width: '100%',
  },
  powerOrbit: {
    borderColor: 'transparent',
    borderBottomColor: vexTheme.colors.accentMuted,
    borderRadius: 76,
    borderRightColor: vexTheme.colors.accentMuted,
    borderTopColor: vexTheme.colors.accentStrong,
    borderWidth: 4,
    height: 150,
    position: 'absolute',
    width: 150,
  },
  powerText: {
    color: vexTheme.colors.text,
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 28,
    maxWidth: 176,
    minWidth: 0,
    textAlign: 'center',
  },
  powerSubtext: {
    color: vexTheme.colors.textSecondary,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 8,
    textAlign: 'center',
  },
  protocolSpacer: {
    alignSelf: 'center',
    minHeight: 2,
  },
  serverChip: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: vexTheme.colors.surface,
    borderColor: vexTheme.colors.line,
    borderRadius: vexTheme.radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    maxWidth: maxContentWidth,
    minHeight: 62,
    paddingHorizontal: 10,
    width: '100%',
  },
  serverChipDisabled: {
    opacity: 0.72,
  },
  serverChipIcon: {
    alignItems: 'center',
    backgroundColor: vexTheme.colors.accentMuted,
    borderColor: vexTheme.colors.accentLine,
    borderRadius: 14,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  serverChipCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverChipCaption: {
    color: vexTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  serverChipLabel: {
    color: vexTheme.colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
    minWidth: 0,
  },
  serverLatencyPill: {
    alignItems: 'center',
    backgroundColor: vexTheme.colors.accentMuted,
    borderColor: vexTheme.colors.accentLine,
    flexDirection: 'row',
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minWidth: 60,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  serverLatencyText: {
    color: vexTheme.colors.accentStrong,
    fontSize: 13,
    fontWeight: '900',
  },
  trafficStats: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: vexTheme.colors.surfaceMuted,
    borderColor: vexTheme.colors.line,
    borderRadius: vexTheme.radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    maxWidth: maxContentWidth,
    minHeight: 62,
    paddingHorizontal: 14,
    width: '100%',
  },
  trafficItem: {
    flex: 1,
    minWidth: 0,
  },
  trafficLabel: {
    color: vexTheme.colors.textMuted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  trafficValueRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginTop: 5,
  },
  trafficValue: {
    color: vexTheme.colors.text,
    fontSize: 19,
    fontWeight: '900',
  },
  trafficDirectionBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(34,211,238,0.12)',
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  trafficDivider: {
    backgroundColor: vexTheme.colors.line,
    height: 38,
    marginHorizontal: 14,
    width: 1,
  },
  serverModal: {
    backgroundColor: '#020A0B',
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: Platform.OS === 'android' ? 34 : 46,
  },
  serverModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  serverModalEyebrow: {
    color: '#22D3EE',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 4,
  },
  serverModalTitle: {
    color: '#F4FCFD',
    fontSize: 20,
    fontWeight: '900',
  },
  serverModalSubtitle: {
    color: '#8FBEC6',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    marginTop: 4,
    maxWidth: 240,
  },
  serverModalClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  serverModalList: {
    gap: 7,
    paddingBottom: 18,
  },
  serverRow: {
    alignItems: 'center',
    backgroundColor: 'rgba(7,17,19,0.84)',
    borderColor: 'rgba(96,118,123,0.3)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 56,
    paddingHorizontal: 10,
  },
  serverRowSelected: {
    backgroundColor: 'rgba(34,211,238,0.14)',
    borderColor: '#22D3EE',
  },
  serverRowDisabled: {
    opacity: 0.62,
  },
  serverRowMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  serverRowFlag: {
    fontSize: 20,
    textAlign: 'center',
  },
  serverRowFlagBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(2,10,11,0.56)',
    borderRadius: 12,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  serverRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  serverRowName: {
    color: '#CFE4E8',
    fontSize: 15,
    fontWeight: '900',
  },
  serverRowNameSelected: {
    color: '#F4FCFD',
  },
  serverRowStatus: {
    color: '#8FBEC6',
    fontSize: 12,
    fontWeight: '700',
  },
  serverRowStatusLine: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 4,
    minWidth: 0,
  },
  serverHealthDot: {
    backgroundColor: '#78969C',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  serverHealthDotActive: {
    backgroundColor: '#22D3EE',
  },
  serverRowLatency: {
    color: '#A7B9BD',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  serverRowSide: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minWidth: 76,
    justifyContent: 'flex-end',
  },
  serverRowLatencySelected: {
    color: '#B9FBFF',
  },
  serverModalHint: {
    color: '#8FBEC6',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    paddingBottom: 18,
    textAlign: 'center',
  },
  vpnErrorText: {
    alignSelf: 'center',
    color: '#FF9F9F',
    fontSize: 12,
    fontWeight: '700',
    maxWidth: maxContentWidth - 32,
    textAlign: 'center',
  },
  vpnNoticeText: {
    color: vexTheme.colors.warning,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  rotationNotice: {
    alignSelf: 'center',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
