#!/usr/bin/env python3
"""Compile and exercise the real PSK event consumer with real queue/store/model types."""
import pathlib, subprocess, tempfile, textwrap, sys
root=pathlib.Path(sys.argv[1]) if len(sys.argv)==2 else pathlib.Path(__file__).resolve().parents[2]
src=root/'macos-native/Sources/VEXNativeMac'
with tempfile.TemporaryDirectory(prefix='native-psk-consumer-',dir='/private/tmp') as temp:
 t=pathlib.Path(temp); main=t/'main.swift'; binary=t/'fixture'
 main.write_text(textwrap.dedent(r'''
 import Foundation
 @main @MainActor struct Fixture {
   static let owner=NativePushPSKEventOwner(accountID:"account-A",installationID:"install-A")!
   static let other=NativePushPSKEventOwner(accountID:"account-B",installationID:"install-B")!
   static let device="11111111-1111-4111-8111-111111111111", rotation="22222222-2222-4222-8222-222222222222", psk="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
   final class Log { var v:[String]=[] }
   static func need(_ ok:Bool,_ m:String){if !ok {fputs("FAIL: \(m)\n",stderr);exit(1)}}
   static func envelope(_ version:Int=5)->PSKRotationCurrentResponse { try! JSONDecoder().decode(PSKRotationCurrentResponse.self,from:JSONSerialization.data(withJSONObject:["rotation_id":rotation,"activate":false,"current_version":version-1,"profile_version":version,"profile_digest":"sha256:"+String(repeating:"a",count:64),"deadline_at":"2026-10-03T00:00:00Z","profile":["version":version,"device_id":device,"preshared_key":psk]])) }
   static func event(_ kind:NativePushPSKEvent.Kind,_ id:String,_ version:Int=5)->NativePushPSKEvent { NativePushPSKEvent(kind:kind,eventID:id,rotationID:rotation,deviceID:device,profileVersion:version,deadlineAt:nil) }
   @MainActor static func deps(_ scope:@escaping()->Bool={true}, fetch:@escaping()->PSKRotationCurrentResponse, ack:@escaping()->PSKRotationACKResponse, log:Log)->NativePSKEventConsumer.Dependencies {
     NativePSKEventConsumer.Dependencies(scopeIsCurrent:scope,fetchCurrent:{log.v.append("fetch");return fetch()},validate:{ e,x in log.v.append("validate");need(e.rotationID==x.rotationID&&e.profileVersion==x.profileVersion,"event geometry")},acknowledge:{ e in log.v.append("ack");return ack()},activate:{ _,_ in log.v.append("activate")})
   }
   @MainActor static func queue(_ root:URL,_ items:[NativePushPSKEvent], owner:NativePushPSKEventOwner=owner){let q=NativePushPSKEventQueue(appDataURL:root);for e in items {try! q.enqueue(e,owner:owner)}}
   @MainActor static func remaining(_ root:URL,_ owner:NativePushPSKEventOwner=owner)->[NativePushPSKEvent]{try! NativePushPSKEventQueue(appDataURL:root).events(owner:owner)}
   @MainActor static func run(_ name:String,_ block:(URL)->Void){let d=URL(fileURLWithPath:"/private/tmp/consumer-\(name)-\(UUID().uuidString)",isDirectory:true);defer{try? FileManager.default.removeItem(at:d)};block(d)}
   static func main() async {
     run("stage") { d in let l=Log();queue(d,[event(.profile_updated,"u")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=deps(fetch:{envelope()},ack:{PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},log:l);Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["fetch","validate","validate","ack"],"stage save/reload before ack order");need(remaining(d).isEmpty,"acked update removed");need(try! NativePSKStagedProfileStore(appDataURL:d).load(owner:owner,managedDeviceID:device,rotationID:rotation) != nil,"stage retained")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("failure") { d in let l=Log();queue(d,[event(.profile_updated,"u")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{true},fetchCurrent:{throw CocoaError(.fileReadUnknown)},validate:{_,_ in l.v.append("validate")},acknowledge:{_ in l.v.append("ack");return PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1&&l.v.isEmpty,"fetch failure retained/no activation")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("ack") { d in let l=Log();queue(d,[event(.profile_updated,"u")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=deps(fetch:{envelope()},ack:{PSKRotationACKResponse(rotationID:"33333333-3333-4333-8333-333333333333",accepted:true,replayed:false)},log:l);Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1,"ack mismatch retained");need(try! NativePSKStagedProfileStore(appDataURL:d).load(owner:owner,managedDeviceID:device,rotationID:rotation) != nil,"ack mismatch stage retained")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("cutover") { d in let l=Log();queue(d,[event(.cutover_ready,"c")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=deps(fetch:{envelope()},ack:{PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},log:l);Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1&&l.v.isEmpty,"out of order cutover retained");try! NativePSKStagedProfileStore(appDataURL:d).stage(envelope(),owner:owner,managedDeviceID:device);await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["validate","activate"],"positive cutover");need(remaining(d).isEmpty,"cutover removed");need(try! NativePSKStagedProfileStore(appDataURL:d).load(owner:owner,managedDeviceID:device,rotationID:rotation)==nil,"cutover purged")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("isolation") { d in queue(d,[event(.profile_updated,"a")],owner:other);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let l=Log();let dp=deps(fetch:{envelope()},ack:{PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},log:l);Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d,other).count==1&&l.v.isEmpty,"owner isolation")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("scope") { d in var current=true;let l=Log();queue(d,[event(.profile_updated,"u")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{current},fetchCurrent:{current=false;return envelope()},validate:{_,_ in l.v.append("validate")},acknowledge:{_ in l.v.append("ack");return PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1&&l.v.isEmpty,"scope changed after await retained")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
     run("tamper") { d in let l=Log();queue(d,[event(.profile_updated,"t")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));var checks=0;let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{checks += 1;if checks>=5, let urls=FileManager.default.enumerator(at:d,includingPropertiesForKeys:nil), let url=urls.compactMap({$0 as? URL}).first(where: {$0.lastPathComponent.hasPrefix("staged-")}) {try! Data("{}".utf8).write(to:url)};return true},fetchCurrent:{envelope()},validate:{_,_ in l.v.append("validate")},acknowledge:{_ in l.v.append("ack");return PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1 && !l.v.contains("ack"),"disk replacement before reread has no ACK")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    run("later") { d in let l=Log();let bad=event(.profile_updated,"bad"),good=event(.profile_updated,"good");queue(d,[bad,good]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));var calls=0;let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{true},fetchCurrent:{envelope()},validate:{_,_ in calls += 1;if calls==1 {throw CocoaError(.fileReadCorruptFile)};l.v.append("valid")},acknowledge:{_ in l.v.append("ack");return PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).map(\.eventID)==["bad"],"validation failure does not block later event")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    run("wrong-device") { d in let l=Log();let wrong=NativePushPSKEvent(kind:.profile_updated,eventID:"wrong",rotationID:rotation,deviceID:"other-device",profileVersion:5,deadlineAt:nil);queue(d,[wrong,event(.profile_updated,"good")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=deps(fetch:{envelope()},ack:{PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},log:l);Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).map(\.eventID)==["wrong"],"wrong device skips without blocking")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    run("activation-retry") { d in let l=Log();try! NativePSKStagedProfileStore(appDataURL:d).stage(envelope(),owner:owner,managedDeviceID:device);queue(d,[event(.cutover_ready,"c")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));var fail=true;let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{true},fetchCurrent:{envelope()},validate:{_,_ in ()},acknowledge:{_ in PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate");if fail {fail=false;throw CocoaError(.fileWriteUnknown)}});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(remaining(d).count==1 && (try! NativePSKStagedProfileStore(appDataURL:d).load(owner:owner,managedDeviceID:device,rotationID:rotation) != nil),"activation failure retains stage/event");await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["activate","activate"] && remaining(d).isEmpty,"activation retry succeeds once after failure")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    run("cleanup-failure") { d in let l=Log();try! NativePSKStagedProfileStore(appDataURL:d).stage(envelope(),owner:owner,managedDeviceID:device);queue(d,[event(.cutover_ready,"c")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d),cleanupStage:{_,_,_ in throw CocoaError(.fileWriteUnknown)});let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{true},fetchCurrent:{envelope()},validate:{_,_ in ()},acknowledge:{_ in PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in l.v.append("activate")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["activate"]&&remaining(d).isEmpty,"cleanup failure removes trigger/no duplicate activation");need(try! NativePSKStagedProfileStore(appDataURL:d).load(owner:owner,managedDeviceID:device,rotationID:rotation) != nil,"cleanup failure keeps stage");await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["activate"],"orphan stage cannot retrigger")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    run("failure-callback") { d in let l=Log();queue(d,[event(.profile_updated,"f")]);let c=NativePSKEventConsumer(queue:NativePushPSKEventQueue(appDataURL:d),store:NativePSKStagedProfileStore(appDataURL:d));let dp=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{true},fetchCurrent:{throw CocoaError(.fileReadUnknown)},validate:{_,_ in ()},acknowledge:{_ in PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in ()},didFail:{_ in l.v.append("failure")});Task{@MainActor in await c.process(owner:owner,managedDeviceID:device,dependencies:dp);need(l.v==["failure"],"current failure reports once");let stale=NativePSKEventConsumer.Dependencies(scopeIsCurrent:{false},fetchCurrent:{throw CocoaError(.fileReadUnknown)},validate:{_,_ in ()},acknowledge:{_ in PSKRotationACKResponse(rotationID:rotation,accepted:true,replayed:false)},activate:{_,_ in ()},didFail:{_ in l.v.append("stale")});await c.process(owner:owner,managedDeviceID:device,dependencies:stale);need(l.v==["failure"],"stale failure cannot overwrite")};RunLoop.current.run(until:Date().addingTimeInterval(0.1)) }
    print("runtime fixture passed: stage/reload/ack, failures, out-of-order retry, cutover, owner isolation, scope cancellation")
   }
 }
 '''))
 files=[src/'Models/VEXModels.swift',src/'Services/NativePushSecureFileStore.swift',src/'Services/NativePushPSKEventQueue.swift',src/'Services/NativePSKStagedProfileStore.swift',src/'Services/NativePSKEventConsumer.swift',main]
 c=subprocess.run(['swiftc', str(__import__("pathlib").Path(__file__).resolve().parents[2]/"macos-native/Sources/VEXNativeMac/Services/NativePSKIdentifier.swift"), '-parse-as-library',*map(str,files),'-o',str(binary)],text=True,capture_output=True);print(c.stdout,end='');print(c.stderr,end='',file=sys.stderr)
 if c.returncode: raise SystemExit(c.returncode)
 r=subprocess.run([str(binary)],text=True,capture_output=True);print(r.stdout,end='');print(r.stderr,end='',file=sys.stderr);raise SystemExit(r.returncode)
