#!/usr/bin/env python3
"""Offline runtime proof for the native signed-profile verifier (no app or VPN launch)."""
import pathlib, subprocess, tempfile, textwrap
ROOT = pathlib.Path(__file__).resolve().parents[2]
MODELS = ROOT / "macos-native/Sources/VEXNativeMac/Models/VEXModels.swift"
VERIFIER = ROOT / "macos-native/Sources/VEXNativeMac/Services/NativeVPNProfileAuthorizationVerifier.swift"
GO = r'''package main
import("crypto/ecdsa";"crypto/elliptic";"crypto/rand";"crypto/sha256";"crypto/x509";"encoding/base64";"encoding/json";"os";"time")
func main(){ k,_:=ecdsa.GenerateKey(elliptic.P256(),rand.Reader); now:=time.Now().UTC().Truncate(time.Second); policy:=map[string]any{"schema":"vex.native-vpn-profile.v1","user_id":"owner","device_id":"device","assigned_location_id":"loc","routing_mode":"full_tunnel","profile_version":7,"issued_at":now.Format(time.RFC3339),"expires_at":now.Add(time.Hour).Format(time.RFC3339),"tunnel":map[string]any{"protocol":"wireguard","endpoint":"vpn.example:51820","assigned_ipv4":"10.0.0.2/32","server_public_key":"server","preshared_key":"psk","dns":[]string{"1.1.1.1"},"allowed_ips":[]string{"0.0.0.0/0"},"mtu":1420,"persistent_keepalive":55}}
 p,_:=json.Marshal(policy); d:=sha256.Sum256(p); sig,_:=ecdsa.SignASN1(rand.Reader,k,d[:]); der,_:=x509.MarshalPKIXPublicKey(&k.PublicKey); out:=map[string]any{"der":base64.RawURLEncoding.EncodeToString(der),"envelope":map[string]any{"rotation_id":"r","activate":false,"current_version":7,"profile_version":7,"profile_digest":"d","deadline_at":now.Add(time.Hour).Format(time.RFC3339),"profile":map[string]any{"version":7,"protocol":"wireguard","server":"vpn.example","port":51820,"server_public_key":"server","preshared_key":"psk","assigned_ipv4":"10.0.0.2/32","dns":[]string{"1.1.1.1"},"allowed_ips":[]string{"0.0.0.0/0"},"expires_at":now.Add(time.Hour).Format(time.RFC3339),"authorization":map[string]any{"algorithm":"ECDSA_P256_SHA256_DER","key_id":"k","payload_base64":base64.RawURLEncoding.EncodeToString(p),"signature_base64":base64.RawURLEncoding.EncodeToString(sig)}}}}; json.NewEncoder(os.Stdout).Encode(out)}'''
HARNESS = r'''
import Foundation
struct Fixture: Decodable { let der: String; let envelope: PSKRotationCurrentResponse }
let fixture = try! JSONDecoder().decode(Fixture.self, from: Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[1])))
let der = Data(base64Encoded: fixture.der.replacingOccurrences(of:"-",with:"+").replacingOccurrences(of:"_",with:"/") + String(repeating:"=",count:(4-fixture.der.count%4)%4))!
let verifier = NativeVPNProfileAuthorizationVerifier(pinnedPublicKeyDER:["k":der])
func rejected(_ name:String, _ e: PSKRotationCurrentResponse = fixture.envelope, _ owner:String="owner", _ device:String="device", _ loc:String="loc", _ route:String="full_tunnel", keys _keys:[String:Data]=["k":der], now _now:Date=Date()) { do { _=try NativeVPNProfileAuthorizationVerifier(pinnedPublicKeyDER:_keys).verify(e,ownerAccountID:owner,managedDeviceID:device,locationID:loc,routingMode:route,now:_now); fatalError("accepted \(name)") } catch {} }
let verified=try! verifier.verifyDetailed(fixture.envelope,ownerAccountID:"owner",managedDeviceID:"device",locationID:"loc",routingMode:"full_tunnel"); precondition(verified.envelope.profile.authorization == nil); precondition(verified.mtu == 1420 && verified.persistentKeepalive == 55); let clean=try! verifier.verify(fixture.envelope,ownerAccountID:"owner",managedDeviceID:"device",locationID:"loc",routingMode:"full_tunnel"); precondition(clean.profile.authorization == nil)
rejected("unknownkey", fixture.envelope, keys:["other":der]); var x=fixture.envelope; x.profile.authorization!.payloadBase64 += "A"; rejected("tamperedpayload",x); x=fixture.envelope; x.profile.authorization!.signatureBase64="A"; rejected("tamperedsignature",x); x=fixture.envelope; x.profile.server="evil"; rejected("profilefield",x); x=fixture.envelope; x.profile.presharedKey="other-psk"; rejected("psk",x); x=fixture.envelope; x.profile.amnezia=try! JSONDecoder().decode(ManagedVpnAmnezia.self, from: Data("{\"jc\":1}".utf8)); rejected("awg",x); x=fixture.envelope; x.profile.allowedIps=["10.0.0.0/8"]; rejected("routingfield",x); rejected("owner",fixture.envelope,"wrong"); rejected("device",fixture.envelope,"owner","wrong"); rejected("location",fixture.envelope,"owner","device","wrong"); rejected("routing",fixture.envelope,"owner","device","loc","wrong"); x=fixture.envelope; x.profileVersion=8; rejected("version",x); rejected("time",fixture.envelope,"owner","device","loc","full_tunnel", now: Date(timeIntervalSince1970: 1)); x=fixture.envelope; x.profile.authorization=nil; rejected("missingauth",x); rejected("missinganchor",fixture.envelope,keys:[:]); print("NativeVPNProfileAuthorizationVerifier runtime: PASS")
'''
with tempfile.TemporaryDirectory() as d:
 d=pathlib.Path(d); (d/'fixture.go').write_text(GO); (d/'fixture.json').write_bytes(subprocess.check_output(['go','run',str(d/'fixture.go')]))
 (d/'main.swift').write_text(HARNESS)
 subprocess.run(['swiftc',str(MODELS),str(VERIFIER),str(d/'main.swift'),'-o',str(d/'verify')],check=True)
 subprocess.run([str(d/'verify'),str(d/'fixture.json')],check=True)
