#!/usr/bin/env python3
"""Run the real prepared-tunnel body with gated fake helper/profile boundaries only."""
from pathlib import Path
import subprocess,sys,tempfile
root=Path(__file__).resolve().parents[2]; source=Path(sys.argv[1]) if len(sys.argv)==2 else root/'macos-native/Sources/VEXNativeMac/Stores/VEXAppState.swift'; source=source/'macos-native/Sources/VEXNativeMac/Stores/VEXAppState.swift' if source.is_dir() else source; s=source.read_text()
def ext(mark):
 a=s.index(mark); b=s.index('{',a); n=1; i=b+1
 while n: n+=(s[i]=='{')-(s[i]=='}'); i+=1
 return s[a:i]
prepared=ext('    private func connectPreparedTunnel(').replace('private func connectPreparedTunnel','func connectPreparedTunnel',1)
if 'sessionGeneration: Int? = nil' not in prepared:
 prepared += '''\n    func connectPreparedTunnel(_ tunnel: PreparedTunnel, helper: Helper, generation: Int, resiliencePolicy: ResiliencePolicy? = nil, sessionGeneration: Int? = nil, accessToken token: String? = nil, accountID: String? = nil) async throws -> PreparedTunnel { try await connectPreparedTunnel(tunnel, helper: helper, generation: generation, resiliencePolicy: resiliencePolicy) }\n'''
guard=ext('    private func ensureConnectStillDesired(').replace('private func ensureConnectStillDesired','func ensureConnectStillDesired',1)
auth_guard=ext('    private func ensureAuthenticatedSessionCurrent(').replace('private func ensureAuthenticatedSessionCurrent','func ensureAuthenticatedSessionCurrent',1) if '    private func ensureAuthenticatedSessionCurrent(' in s else '' # Unused in exact legacy caller/guard; no fake auth-check implementation.
h=r'''import Foundation
struct User {let id:String}; struct Session {let user:User;let accessToken:String}
enum AuthenticatedOperationError:Error{case sessionChanged}; enum VpnAutopilotRuntimeError:Error{case connectFailed(String)}
struct Dev{let id:String="d"}; struct PreparedTunnel { let locationId:String="l"; let endpoint:String?="e"; let configEndpoint:String?=nil; let config:String="c"; let device=Dev(); func withEndpoint(_ x:String)->PreparedTunnel?{self} }; typealias VEXHelperModel = Helper; typealias VpnStatus = Status; final class LastTunnelEndpointStore { func save(_ endpoint:String, locationId:String){} }
struct ResilienceConnectionCandidate { let endpoint:String="e" }; struct ResiliencePolicy{}
struct Status { var routeOk=false;var socketExists=false;var latestHandshake:UInt64?=nil;var rxBytes:UInt64=0 }; @MainActor final class Helper { var status=Status();var lastConnectAdmissionRejected=false;var message:String?=nil;var ready=0;var connects=0;var disconnects=0;var stage="";unowned let app:H;init(_ a:H){app=a};func ensureHelperReady()async throws{ready+=1;if stage=="ready"{app.authenticatedSessionGeneration+=1}};func connect(antiLeakEnabled:Bool)async{connects+=1;if stage=="connect"{app.authenticatedSessionGeneration+=1}};func disconnect(releaseAntiLeak:Bool)async->Bool{disconnects+=1;return true} }
@MainActor final class Profile { unowned let app:H;init(_ a:H){app=a};var writes=0;func writeHelperConfig(for:PreparedTunnel,validateCurrent:@MainActor () throws -> Void = {})async throws{try validateCurrent();writes+=1;if app.stage=="write"{app.authenticatedSessionGeneration+=1};try validateCurrent()} }
@MainActor final class Auto {func fallbackTunnels(for tunnel:PreparedTunnel)->[PreparedTunnel]{[tunnel]} }; @MainActor final class Dynamic {func orderedCandidates(for:PreparedTunnel,policy:ResiliencePolicy)->[ResilienceConnectionCandidate]{[]};func recordSuccess(_:ResilienceConnectionCandidate,policy:ResiliencePolicy){};func recordFailure(_:ResilienceConnectionCandidate,policy:ResiliencePolicy){} }
@MainActor final class H { enum Desired {case connected};var desiredVpnState=Desired.connected;var vpnOperationGeneration=1;var authenticatedSessionGeneration=1;var sessionToken:String?="t";var account="a";var activeResilienceRoute:ResilienceConnectionCandidate?;var antiLeakEnabled=false;var stage="";lazy var profileService=Profile(self);let autopilotService=Auto();let dynamicRouteEngine=Dynamic();var session:Session? = .init(user:.init(id:"a"),accessToken:"t"); var accessToken:String? { sessionToken }
'''+auth_guard+'\n'+guard+'\n'+prepared+r'''
 func verifiedHandshake(for:PreparedTunnel,helper:Helper,previousStatus:Status,startedAt:Date,generation:Int,sessionGeneration:Int?=nil,accessToken:String?=nil,accountID:String?=nil)async throws->Bool{if stage=="handshake"{authenticatedSessionGeneration+=1};return true};func dynamicRouteTransport(_:ResilienceConnectionCandidate)->String{"x"};func submitRouteDiagnostics(connectionEvent:String,transportFrom:String?,transportTo:String?,status:String,helperStatus:Status?,sessionGeneration:Int?=nil,accessToken:String?=nil,accountID:String?=nil){} }
@main struct Main{@MainActor static func main()async{var failures=0;for stage in ["ready","write","connect","handshake"]{let a=H();a.stage=stage;let helper=Helper(a);helper.stage=stage;var stopped=false;do{_ = try await a.connectPreparedTunnel(PreparedTunnel(),helper:helper,generation:1,sessionGeneration:1,accessToken:"t",accountID:"a")}catch AuthenticatedOperationError.sessionChanged{stopped=true}catch{print("stage=\(stage) unexpected=\(error)");failures+=1};let counters="ready=\(helper.ready),write=\(a.profileService.writes),connect=\(helper.connects),disconnect=\(helper.disconnects)";print("stage=\(stage) stopped=\(stopped) \(counters)");if !stopped{failures+=1}};let current=H();let currentHelper=Helper(current);let result=try! await current.connectPreparedTunnel(PreparedTunnel(),helper:currentHelper,generation:1,sessionGeneration:1,accessToken:"t",accountID:"a");let valid=result.locationId=="l" && currentHelper.ready==1 && current.profileService.writes==1 && currentHelper.connects==1;print("valid_current=\(valid)");if !valid{failures+=1};exit(failures==0 ? 0 : 1)}}
'''
with tempfile.TemporaryDirectory(prefix='vex-prepared-auth-') as d:
 p=Path(d);(p/'main.swift').write_text(h);q=subprocess.run(['swiftc','-swift-version','5','-parse-as-library',str(p/'main.swift'),'-o',str(p/'p')],text=True,capture_output=True);print(q.stdout,end='');print(q.stderr,end='',file=__import__('sys').stderr);raise SystemExit(q.returncode or subprocess.run([str(p/'p')]).returncode)
