#!/usr/bin/env python3
"""Compile and execute the real staged-profile store against real model and FD-store types."""
import pathlib, subprocess, tempfile, textwrap, sys
root=pathlib.Path(sys.argv[1]) if len(sys.argv)==2 else pathlib.Path(__file__).resolve().parents[2]; src=root/'macos-native/Sources/VEXNativeMac'
with tempfile.TemporaryDirectory(prefix='native-psk-stage-', dir='/private/tmp') as temp:
 t=pathlib.Path(temp); main=t/'main.swift'; binary=t/'fixture'
 main.write_text(textwrap.dedent(r'''
 import Foundation
 import CryptoKit
 @main struct Fixture {
 static let owner=NativePushPSKEventOwner(accountID:"account-A",installationID:"install-A")!
 static let device="11111111-1111-4111-8111-111111111111", rotation="22222222-2222-4222-8222-222222222222", psk="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
 static func envelope(_ edit:(inout [String:Any])->Void={_ in}) throws -> PSKRotationCurrentResponse { var x:[String:Any]=["rotation_id":rotation,"activate":false,"current_version":4,"profile_version":5,"profile_digest":"sha256:"+String(repeating:"a",count:64),"deadline_at":"2026-10-03T00:00:00Z","profile":["version":5,"device_id":device,"preshared_key":psk]]; edit(&x); return try JSONDecoder().decode(PSKRotationCurrentResponse.self,from:JSONSerialization.data(withJSONObject:x)) }
 static func need(_ ok:Bool,_ m:String){if !ok {fputs("FAIL: \(m)\n",stderr);exit(1)}}
 static func jsonFile(_ root:URL)->URL { FileManager.default.enumerator(at:root,includingPropertiesForKeys:nil)!.compactMap{$0 as? URL}.first{$0.pathExtension=="json" && !$0.lastPathComponent.hasPrefix("staged-index-")}! }
 static func ownerHash(_ owner:NativePushPSKEventOwner)->String { let b=[owner.accountID,owner.installationID].map{Data($0.utf8)};let d=Data(b.enumerated().flatMap{ _,x in var l=UInt64(x.count).bigEndian;return withUnsafeBytes(of:&l){Array($0)}+Array(x)});return SHA256.hash(data:d).map{String(format:"%02x",$0)}.joined() }
 static func indexFile(_ root:URL,_ owner:NativePushPSKEventOwner)->URL { let name="staged-index-"+ownerHash(owner)+".json";return FileManager.default.enumerator(at:root,includingPropertiesForKeys:nil)!.compactMap{$0 as? URL}.first{$0.lastPathComponent==name}! }
 static func stageFile(_ root:URL,_ owner:NativePushPSKEventOwner,_ device:String,_ rotation:String)->URL { let key=ownerHash(owner); let bytes=[key,device,rotation].map{Data($0.utf8)}; let d=Data(bytes.enumerated().flatMap{ _,x in var l=UInt64(x.count).bigEndian;return withUnsafeBytes(of:&l){Array($0)}+Array(x)}); return indexFile(root, owner).deletingLastPathComponent().appendingPathComponent("staged-"+SHA256.hash(data:d).map{String(format:"%02x",$0)}.joined()+".json") }
 static func rejected(_ s:NativePSKStagedProfileStore,_ e:PSKRotationCurrentResponse,_ m:String){do{try s.stage(e,owner:owner,managedDeviceID:device);need(false,m)}catch{}}
 static func main() throws {
   let dir=URL(fileURLWithPath:"/private/tmp/fixture-\(UUID().uuidString)",isDirectory:true);defer{try? FileManager.default.removeItem(at:dir)};let s=NativePSKStagedProfileStore(appDataURL:dir);let q=NativePushPSKEventQueue(appDataURL:dir);let e=try envelope { v in var p=v["profile"] as! [String:Any];p["authorization"]=["algorithm":"ECDSA_P256_SHA256_DER","key_id":"pinned-key-1","payload_base64":"eyJ2IjoxfQ","signature_base64":Data([0x30,0x44,0x02,0x20]+Array(repeating:1,count:32)+[0x02,0x20]+Array(repeating:2,count:32)).base64EncodedString().replacingOccurrences(of:"=",with:"")];v["profile"]=p };try s.stage(e,owner:owner,managedDeviceID:device)
   let restarted=try NativePSKStagedProfileStore(appDataURL:dir).load(owner:owner,managedDeviceID:device,rotationID:rotation);need(restarted?.envelope.profile.presharedKey==psk && restarted?.envelope.profile.authorization?.algorithm=="ECDSA_P256_SHA256_DER" && restarted?.envelope.profile.authorization?.keyID=="pinned-key-1","signed restart exact authorization")
   for bad in [NativePushPSKEventOwner(accountID:"other",installationID:"install-A")!,NativePushPSKEventOwner(accountID:"account-A",installationID:"other")!] {need(try s.load(owner:bad,managedDeviceID:device,rotationID:rotation)==nil,"owner namespace isolation")};need(try s.load(owner:owner,managedDeviceID:"33333333-3333-4333-8333-333333333333",rotationID:rotation)==nil,"device isolation");need(try s.load(owner:owner,managedDeviceID:device,rotationID:"44444444-4444-4444-8444-444444444444")==nil,"rotation isolation")
   for edit in [{(v:inout [String:Any])in v["activate"]=true},{(v:inout [String:Any])in v["profile_version"]=4},{(v:inout [String:Any])in v["profile_digest"]="sha256:bad"},{(v:inout [String:Any])in v["deadline_at"]="never"},{(v:inout [String:Any])in var p=v["profile"] as![String:Any];p["device_id"]="other";v["profile"]=p},{(v:inout [String:Any])in var p=v["profile"] as![String:Any];p["preshared_key"]="not-base64";v["profile"]=p},{(v:inout [String:Any])in var p=v["profile"] as![String:Any];p["config"]="private";v["profile"]=p}] {rejected(s,try envelope(edit),"invalid envelope accepted")}
   let path=jsonFile(dir);let raw=try Data(contentsOf:path);let attrs=try FileManager.default.attributesOfItem(atPath:path.path);need((attrs[.posixPermissions] as? NSNumber)?.intValue==0o600,"file mode")
   let rawText=String(data:raw,encoding:.utf8)!;need(!rawText.contains("account-A") && !rawText.contains("install-A") && !rawText.lowercased().contains("private") && !rawText.lowercased().contains("session"),"raw secret record hygiene")
   var shape=try JSONSerialization.jsonObject(with:raw) as! [String:Any];var profile=(shape["envelope"] as! [String:Any])["profile"] as! [String:Any];var auth=profile["authorization"] as! [String:Any];auth["unknown_secret"]="x";profile["authorization"]=auth;var outer=shape["envelope"] as! [String:Any];outer["profile"]=profile;shape["envelope"]=outer;try JSONSerialization.data(withJSONObject:shape).write(to:path);let malformed=try Data(contentsOf:path);rejected(s,e,"unknown authorization overwritten");need(try Data(contentsOf:path)==malformed,"unknown authorization bytes preserved")
   try Data("{\"x\":1}".utf8).write(to:path);let corrupt=try Data(contentsOf:path);rejected(s,e,"corrupt existing overwritten");need(try Data(contentsOf:path)==corrupt,"corrupt bytes preserved")
   try Data(repeating:65,count:1_048_577).write(to:path);let oversized=try Data(contentsOf:path);rejected(s,e,"oversized existing overwritten");need(try Data(contentsOf:path)==oversized,"oversized bytes preserved")
   try raw.write(to:path);try s.stage(e,owner:owner,managedDeviceID:device);need(try Data(contentsOf:path)==raw,"identical dedupe")
   // Owner tuple index: ACK/event metadata is deliberately absent, but cleanup still removes secret stages.
   let rotation2="55555555-5555-4555-8555-555555555555", device2="66666666-6666-4666-8666-666666666666"
   let e2=try envelope { $0["rotation_id"]=rotation2; var p=$0["profile"] as! [String:Any];p["device_id"]=device2;$0["profile"]=p }; try s.stage(e2,owner:owner,managedDeviceID:device2)
   let other=NativePushPSKEventOwner(accountID:"account-B",installationID:"install-B")!;try s.stage(e,owner:other,managedDeviceID:device)
   let idx=indexFile(dir,owner);let indexBefore=try Data(contentsOf:idx);let indexJSON=try JSONSerialization.jsonObject(with:indexBefore) as! [String:Any];need((indexJSON["tuples"] as! [[String:Any]]).count==2,"two owner tuples indexed")
   try s.purge(owner:owner,managedDeviceID:device,rotationID:rotation);let exactIndex=try JSONSerialization.jsonObject(with:Data(contentsOf:idx)) as! [String:Any];let secondPresent = try s.load(owner:owner,managedDeviceID:device2,rotationID:rotation2) != nil;need((exactIndex["tuples"] as! [[String:Any]]).count==1 && secondPresent,"exact purge updates only tuple index")
   try s.purgeAll(owner:owner);need(try s.load(owner:owner,managedDeviceID:device2,rotationID:rotation2)==nil,"purgeAll removes retained secret stage after metadata ACK absence");need(try s.load(owner:other,managedDeviceID:device,rotationID:rotation) != nil,"purgeAll leaves other owner namespace")
   // Corrupt, oversized, unknown-owner and duplicate indexes are evidence: no secret write may occur.
   try s.stage(e,owner:owner,managedDeviceID:device);let goodIndex=indexFile(dir,owner);let goodIndexBytes=try Data(contentsOf:goodIndex)
   for badIndex in [Data("{\"x\":1}".utf8),Data(repeating:65,count:65_537)] { try badIndex.write(to:goodIndex);rejected(s,e2,"bad index accepted");need(try Data(contentsOf:goodIndex)==badIndex,"bad index bytes changed");need(try s.load(owner:owner,managedDeviceID:device2,rotationID:rotation2)==nil,"bad index wrote secret") }
   var foreign=try JSONSerialization.jsonObject(with:goodIndexBytes) as! [String:Any];foreign["ownerFingerprint"]="00";let foreignBytes=try JSONSerialization.data(withJSONObject:foreign);try foreignBytes.write(to:goodIndex);rejected(s,e2,"foreign index accepted");need(try Data(contentsOf:goodIndex)==foreignBytes,"foreign index bytes changed")
   var duplicate=try JSONSerialization.jsonObject(with:goodIndexBytes) as! [String:Any];var tuples=duplicate["tuples"] as! [[String:Any]];tuples.append(tuples[0]);duplicate["tuples"]=tuples;let duplicateBytes=try JSONSerialization.data(withJSONObject:duplicate);try duplicateBytes.write(to:goodIndex);rejected(s,e2,"duplicate index accepted");need(try Data(contentsOf:goodIndex)==duplicateBytes,"duplicate index bytes changed")
   try goodIndexBytes.write(to:goodIndex);try FileManager.default.removeItem(at:goodIndex);try s.stage(e,owner:owner,managedDeviceID:device);need(FileManager.default.fileExists(atPath:goodIndex.path),"identical stage repairs missing index")
   // Orphan index is safely cleaned; a failed secret destination after index write also leaves no unsafe secret.
   let secret=stageFile(dir,owner,device,rotation);try FileManager.default.removeItem(at:secret);try s.purgeAll(owner:owner);need(!FileManager.default.fileExists(atPath:goodIndex.path),"orphan index cleanup")
   try s.stage(e,owner:owner,managedDeviceID:device);try FileManager.default.removeItem(at:secret);try FileManager.default.createDirectory(at:secret,withIntermediateDirectories:false);do { try s.stage(e,owner:owner,managedDeviceID:device);need(false,"directory secret destination accepted") } catch {};need(FileManager.default.fileExists(atPath:goodIndex.path),"failed secret write loses retry index");do { try s.purgeAll(owner:owner);need(false,"purgeAll directory removal accepted") } catch {};need(FileManager.default.fileExists(atPath:goodIndex.path),"failed purge removed retry index");try FileManager.default.removeItem(at:secret);try s.purgeAll(owner:owner);need(!FileManager.default.fileExists(atPath:goodIndex.path),"retry cleanup after failed secret write")
   // Fill the bounded index without dropping its existing stages; 33rd tuple must fail closed.
   for n in 0..<32 { let d=String(format:"00000000-0000-4000-8000-%012d",n+1);let r=String(format:"10000000-0000-4000-8000-%012d",n+1);let x=try envelope { $0["rotation_id"]=r;var p=$0["profile"] as! [String:Any];p["device_id"]=d;$0["profile"]=p };try s.stage(x,owner:owner,managedDeviceID:d) };let overflowD="20000000-0000-4000-8000-000000000001",overflowR="30000000-0000-4000-8000-000000000001",overflow=try envelope { $0["rotation_id"]=overflowR;var p=$0["profile"] as! [String:Any];p["device_id"]=overflowD;$0["profile"]=p };rejected(s,overflow,"index capacity accepted");let firstRetained = try s.load(owner:owner,managedDeviceID:"00000000-0000-4000-8000-000000000001",rotationID:"10000000-0000-4000-8000-000000000001") != nil;let overflowAbsent = try s.load(owner:owner,managedDeviceID:overflowD,rotationID:overflowR)==nil;need(firstRetained && overflowAbsent,"capacity drops or writes secret")
   need(try q.events(owner:owner).isEmpty,"queue untouched")
   let blocked=URL(fileURLWithPath:"/private/tmp/fixture-blocked-\(UUID().uuidString)");FileManager.default.createFile(atPath:blocked.path,contents:Data());defer{try? FileManager.default.removeItem(at:blocked)};do{try NativePSKStagedProfileStore(appDataURL:blocked).stage(e,owner:owner,managedDeviceID:device);need(false,"write failure accepted")}catch{}
   try s.purge(owner:owner,managedDeviceID:device,rotationID:rotation);need(try s.load(owner:owner,managedDeviceID:device,rotationID:rotation)==nil,"exact owned purge");print("runtime fixture passed: durable isolation validation corruption preservation permissions hygiene queue and purge")
 }}
 '''))
 files=[src/'Models/VEXModels.swift',src/'Services/NativePushPSKEventQueue.swift',src/'Services/NativePushSecureFileStore.swift',src/'Services/NativePSKStagedProfileStore.swift',main]
 c=subprocess.run(['swiftc', str(__import__("pathlib").Path(__file__).resolve().parents[2]/"macos-native/Sources/VEXNativeMac/Services/NativePSKIdentifier.swift"), '-parse-as-library',*map(str,files),'-o',str(binary)],text=True,capture_output=True);print(c.stdout,end='');print(c.stderr,end='',file=sys.stderr)
 if c.returncode: raise SystemExit(c.returncode)
 r=subprocess.run([str(binary)],text=True,capture_output=True);print(r.stdout,end='');print(r.stderr,end='',file=sys.stderr);raise SystemExit(r.returncode)
