// GENERATED by VPN-repo scripts/generate_openapi_schemas.py --client.
// Source of truth: internal/api/dto/types.go (+ domain/app structs) via
// openapi.yaml. DO NOT EDIT BY HAND — regenerate from the VPN repo:
//   python3 scripts/generate_openapi_schemas.py --client
// Every `Contract` alias asserts the spec shape stays assignable to the
// hand-written DTO in ./dto; a violation fails `npm run typecheck` here.

import type {
  AppRemoteConfigResponseDTO,
  AppUpdateCheckResponseDTO,
  AuthResultDTO,
  BillingPlanDTO,
  CheckoutSessionDTO,
  DeviceDTO,
  DeviceIdentityChallengeDTO,
  DeviceUsageDTO,
  DeviceUsageResponseDTO,
  EmailOTPChallengeDTO,
  EntitlementDTO,
  LocationDTO,
  NativeVPNProfileDTO,
  PortalSessionDTO,
  RegisterDevicePushTokenResultDTO,
  RegisterNativeDeviceResultDTO,
  SupportMessageDTO,
  SupportTicketDTO,
  UserDTO,
} from "./dto"

export type VexApiSpecExpect<T extends true> = T

export interface AppRemoteConfigResponseDTOSpec {
  version?: string
  signature?: string
  releasedAt?: null | string
  platform: string
  channel: string
  minSupportedBuild?: number
  recommendedBuild?: number
  recommendedVersion?: string
  coreVersion?: string
  configSchemaVersion?: number
  minConfigSchemaVersion?: number
  minCoreVersion?: string
  supportedApiClientVersions?: string[]
  routingPolicyVersionPrefix?: string
  routingPolicyVersion?: string
  featureFlags?: Record<string, boolean>
  incidentBanner?: string
  checkedAt: string
}
type _AppRemoteConfigResponseDTOContract = VexApiSpecExpect<AppRemoteConfigResponseDTOSpec extends AppRemoteConfigResponseDTO ? true : false>

export interface AppUpdateCheckResponseDTOSpec {
  updateAvailable: boolean
  delivery: string
  required: boolean
  currentBuildBlocked?: boolean
  latestVersion?: string
  latestBuild?: number
  minSupportedBuild?: number
  minConfigSchemaVersion?: number
  downloadUrl?: string
  changelog?: string
  checksumSha256?: string
  signatureUrl?: string
  channel?: string
  reason?: string
  rolloutPercent?: number
  checkedAt: string
}
type _AppUpdateCheckResponseDTOWidened = Omit<AppUpdateCheckResponseDTO, "delivery"> & { "delivery": string }
type _AppUpdateCheckResponseDTOContract = VexApiSpecExpect<AppUpdateCheckResponseDTOSpec extends _AppUpdateCheckResponseDTOWidened ? true : false>

export interface AuthResultDTOSpec {
  user: UserDTOSpec
  session: { id: string } & { user_id: string } & { access_token?: string } & { expires_at: string } & { revoked_at?: null | string } & { created_at: string }
  access_grant?: null | { id: string } & { user_id: string } & { status: string } & { device_limit: number } & { tier: string } & { rate_limit_mbps?: null | number } & { traffic_priority: number } & { expires_at?: null | string } & { active_devices: number } & { remaining_devices: number } & { active: boolean } & { created_at: string } & { updated_at: string }
}
type _AuthResultDTOContract = VexApiSpecExpect<AuthResultDTOSpec extends AuthResultDTO ? true : false>

export interface BillingPlanDTOSpec {
  id: string
  name: string
  provider: string
  provider_price_id?: string
  amount_cents: number
  currency: string
  interval: string
  device_limit: number
  tier: string
  rate_limit_mbps?: null | number
  traffic_priority: number
  visibility: string
  status: string
  created_at: string
}
type _BillingPlanDTOContract = VexApiSpecExpect<BillingPlanDTOSpec extends BillingPlanDTO ? true : false>

export interface CheckoutSessionDTOSpec {
  id: string
  user_id: string
  plan_id: string
  kind: string
  provider: string
  url: string
  status: string
  discount?: null | { referral_reward_id?: string } & { promo_code_id?: string } & { promo_code?: string } & { type: string } & { percent?: number } & { amount_minor?: number } & { currency?: string } & { free_days?: number } & { free_months?: number } & { provider_coupon?: string } & { upgrade_from_plan_id?: string } & { superseded_subscription_id?: string }
  created_at: string
}
type _CheckoutSessionDTOContract = VexApiSpecExpect<CheckoutSessionDTOSpec extends CheckoutSessionDTO ? true : false>

export interface DeviceDTOSpec {
  id: string
  user_id: string
  name: string
  protocol: string
  protocol_label?: string
  status: string
  provisioning_mode: string
  client_key_ownership: string
  external_device_id?: string
  platform?: string
  app_version?: string
  push_provider?: string
  public_key: string
  crypto_profile: string
  psk_epoch: number
  profile_version: number
  psk_rotated_at?: null | string
  billing_plan_id?: string
  billing_tier: string
  rate_limit_mbps?: null | number
  traffic_priority: number
  shield_enabled: boolean
  assigned_ipv4: string
  node_id: string
  node_assignment_reason?: string
  node_assigned_at?: null | string
  last_node_change_at?: null | string
  endpoint?: string
  latency_ms?: null | number
  saved_profiles?: { node_id: string } & { assigned_ipv4: string } & { status: string } & { profile_version: number }[]
  created_at: string
  revoked_at?: null | string
}
type _DeviceDTOContract = VexApiSpecExpect<DeviceDTOSpec extends DeviceDTO ? true : false>

export interface DeviceIdentityChallengeDTOSpec {
  id: string
  nonce: string
  purpose: string
  expires_at: string
}
type _DeviceIdentityChallengeDTOContract = VexApiSpecExpect<DeviceIdentityChallengeDTOSpec extends DeviceIdentityChallengeDTO ? true : false>

export interface DeviceUsageDTOSpec {
  device_id: string
  user_id: string
  node_id: string
  connection_status: string
  connected: boolean
  multiple_devices_detected: boolean
  latest_handshake_at?: null | string
  seconds_since_handshake?: null | number
  rx_bytes: number
  tx_bytes: number
  total_bytes: number
  historical_rx_bytes: number
  historical_tx_bytes: number
  historical_total_bytes: number
  last_nonzero_traffic_at?: null | string
  rate_limit_mbps?: null | number
  traffic_priority: number
  rx_rate_bps?: null | number
  tx_rate_bps?: null | number
}
type _DeviceUsageDTOContract = VexApiSpecExpect<DeviceUsageDTOSpec extends DeviceUsageDTO ? true : false>

export interface DeviceUsageResponseDTOSpec {
  client_ip?: string
  current_device_id?: string
  current_device_by?: string
  usage: DeviceUsageDTOSpec[]
}
type _DeviceUsageResponseDTOContract = VexApiSpecExpect<DeviceUsageResponseDTOSpec extends DeviceUsageResponseDTO ? true : false>

export interface EmailOTPChallengeDTOSpec {
  challenge_id: string
  expires_at: string
}
type _EmailOTPChallengeDTOContract = VexApiSpecExpect<EmailOTPChallengeDTOSpec extends EmailOTPChallengeDTO ? true : false>

export interface EntitlementDTOSpec {
  user_id: string
  active: boolean
  reason: string
  source?: string
  source_id?: string
  plan_id?: string
  subscription_id?: string
  access_grant_id?: string
  display_name?: string
  account_status?: string
  subscription_title?: string
  subscription_subtitle?: string
  remaining_text?: string
  status?: string
  current_period_end?: null | string
  effective_expires_at?: null | string
  switch_bonus_status?: string
  switch_bonus_days?: number
  switch_bonus_until?: null | string
  device_limit: number
  base_device_limit?: number
  addon_device_slots?: number
  max_device_limit?: number
  can_buy_device_addon?: boolean
  device_addon_price_minor?: number
  device_addon_currency?: string
  tier?: string
  rate_limit_mbps?: null | number
  traffic_priority?: number
  active_devices: number
  grace_until?: null | string
  can_create_device: boolean
  vpn_access: boolean
  business_team_id?: string
  business_team_name?: string
  business_role?: string
  dedicated_node_id?: string
  manual_setup_notes?: string
}
type _EntitlementDTOContract = VexApiSpecExpect<EntitlementDTOSpec extends EntitlementDTO ? true : false>

export interface LocationDTOSpec {
  id: string
  country_code: string
  city: string
  flag_emoji?: string
  availability: string
  priority: number
  status: string
  node_count: number
  healthy_nodes: number
  awg3_nodes: number
  average_load_percent: number
  available_slots: number
  endpoint?: string
  latency_ms?: null | number
}
type _LocationDTOContract = VexApiSpecExpect<LocationDTOSpec extends LocationDTO ? true : false>

export interface NativeVPNProfileDTOSpec {
  unchanged?: boolean
  version: number
  revoked: boolean
  rotation_required: boolean
  device_id?: string
  protocol?: string
  server?: string
  port?: number
  server_public_key?: string
  preshared_key?: string
  assigned_ipv4?: string
  dns?: string[]
  allowed_ips?: string[]
  amnezia?: null | { jc?: number } & { jmin?: number } & { jmax?: number } & { s1?: number } & { s2?: number } & { s3?: number } & { s4?: number } & { h1?: string } & { h2?: string } & { h3?: string } & { h4?: string } & { i1?: string } & { i2?: string } & { i3?: string } & { i4?: string } & { i5?: string } & { header_protection_key?: string }
  amnezia_version?: number
  expires_at?: null | string
  config?: string
  bypass_ranges?: string[]
  bypass_domains?: string[]
  routing_policy_version?: string
  authorization?: null | { algorithm: string } & { key_id: string } & { payload_base64: string } & { signature_base64: string }
}
type _NativeVPNProfileDTOContract = VexApiSpecExpect<NativeVPNProfileDTOSpec extends NativeVPNProfileDTO ? true : false>

export interface PortalSessionDTOSpec {
  id: string
  user_id: string
  provider: string
  url: string
  created_at: string
}
type _PortalSessionDTOContract = VexApiSpecExpect<PortalSessionDTOSpec extends PortalSessionDTO ? true : false>

export interface RegisterDevicePushTokenResultDTOSpec {
  device: DeviceDTOSpec
}
type _RegisterDevicePushTokenResultDTOContract = VexApiSpecExpect<RegisterDevicePushTokenResultDTOSpec extends RegisterDevicePushTokenResultDTO ? true : false>

export interface RegisterNativeDeviceResultDTOSpec {
  device_registered: boolean
  device: DeviceDTOSpec
  binding_status: string
  trust_level: string
}
type _RegisterNativeDeviceResultDTOContract = VexApiSpecExpect<RegisterNativeDeviceResultDTOSpec extends RegisterNativeDeviceResultDTO ? true : false>

export interface SupportMessageDTOSpec {
  id: string
  ticket_id: string
  sender: string
  author_id?: string
  body: string
  created_at: string
}
type _SupportMessageDTOContract = VexApiSpecExpect<SupportMessageDTOSpec extends SupportMessageDTO ? true : false>

export interface SupportTicketDTOSpec {
  id: string
  user_id: string
  subject: string
  message: string
  messages?: SupportMessageDTOSpec[]
  status: string
  priority: string
  assigned_admin_user_id?: string
  source: string
  admin_note?: string
  support_rating?: null | number
  support_feedback?: string
  support_rated_at?: null | string
  created_at: string
  updated_at: string
  closed_at?: null | string
}
type _SupportTicketDTOContract = VexApiSpecExpect<SupportTicketDTOSpec extends SupportTicketDTO ? true : false>

export interface UserDTOSpec {
  id: string
  email: string
  mfa_enabled: boolean
  status: string
  created_at: string
  deleted_at?: null | string
}
type _UserDTOContract = VexApiSpecExpect<UserDTOSpec extends UserDTO ? true : false>
